# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Petal-Parser-HTB
version:      1.04
version_from: lib/Petal/Parser/HTB.pm
installdirs:  site
requires:
    HTML::Parser:                  3.45
    HTML::TreeBuilder:             3.12
    Petal:                         1.10

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
